config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :rms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :user
end

app/models/rm.rb
class Rm < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  def index
    @marks = Mark.all
  end

  def show
  end

  def new
    @mark = Mark.new
  end

  def edit
  end

  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mark
      @mark = Mark.find(params[:id])
    end

    def mark_params
      params.require(:mark).permit(:user_id, :content, :quantity, :max)
    end
end

app/controllers/r_ms_controller.rb
class RmsController < ApplicationController
  before_action :set_rm, only: [:show, :edit, :update, :destroy]

  # GET /rms
  # GET /rms.json
  def index
    @rms = Rm.all
  end

  # GET /rms/1
  # GET /rms/1.json
  def show
  end

  # GET /rms/new
  def new
    @rm = Rm.new
  end

  # GET /rms/1/edit
  def edit
  end

  # POST /rms
  # POST /rms.json
  def create
    @rm = Rm.new(rm_params)

    respond_to do |format|
      if @rm.save
        format.html { redirect_to @rm, notice: 'Rm was successfully created.' }
        format.json { render :show, status: :created, location: @rm }
      else
        format.html { render :new }
        format.json { render json: @rm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rms/1
  # PATCH/PUT /rms/1.json
  def update
    respond_to do |format|
      if @rm.update(rm_params)
        format.html { redirect_to @rm, notice: 'Rm was successfully updated.' }
        format.json { render :show, status: :ok, location: @rm }
      else
        format.html { render :edit }
        format.json { render json: @rm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rms/1
  # DELETE /rms/1.json
  def destroy
    @rm.destroy
    respond_to do |format|
      format.html { redirect_to rms_url, notice: 'Rm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rm
      @rm = Rm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rm_params
      params.require(:rm).permit(:user_id, :content, :quantity, :max)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/r_ms_helper.rb
module RMsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # def current_user?(user)
  #   user == current_user
  # end

  # def current_user
  #   if (user_id = session[:user_id])
  #      @current_user ||= User.find_by(id: user_id)
  #    elsif (user_id = cookies.signed[:user_id])
  #      user = User.find_by(id: user_id)
  #      if user && user.authenticated?(:remember, cookies[:remember_token])
  #        log_in user
  #        @current_user = user
  #      end
  #    end
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marks/_form.html.erb
<%= form_for(mark) do |f| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :max %>
    <%= f.text_field :max %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Quantity</th>
      <th>Max</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.user_id %></td>
        <td><%= mark.content %></td>
        <td><%= mark.quantity %></td>
        <td><%= mark.max %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= current_user.inspect %>

<aside class="col-md-8">
  <div class="rm_form">
    <%= form_for(@mark) do |f| %>
      <%#= render 'shared/error_messages', object: f.object %>
      <%= f.select :content, ['Back squat', 'Front squat', 'Deadlift',
                              'Sumo Deadlift', 'Sumo Deadlift High Pull',
                              'Power Snatch', 'Power Clean',
                              'Squat Clean', 'Muscle Snatch',
                              'Clean & Jerk', 'Thruster', 'Push Jerk',
                              'Split Jerk', 'Press',
                              'Push press', 'Cluster', 'Overhead Squat']%>

      <%= f.label :max, "Max reps" %>
      <%= f.text_field :max, class: 'form-control' %>

      <%= f.label :quantity, "Weight lifted" %>
      <%= f.text_field :quantity, class: 'form-control' %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</aside>    

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mark.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @mark.content %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @mark.quantity %>
</p>

<p>
  <strong>Max:</strong>
  <%= @mark.max %>
</p>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>

app/views/r_ms/_form.html.erb
<%= form_for(rm) do |f| %>
  <% if rm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rm.errors.count, "error") %> prohibited this rm from being saved:</h2>

      <ul>
      <% rm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :max %>
    <%= f.text_field :max %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/r_ms/edit.html.erb
<h1>Editing Rm</h1>

<%= render 'form', rm: @rm %>

<%= link_to 'Show', @rm %> |
<%= link_to 'Back', rms_path %>

app/views/r_ms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Quantity</th>
      <th>Max</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rms.each do |rm| %>
      <tr>
        <td><%= rm.user %></td>
        <td><%= rm.content %></td>
        <td><%= rm.quantity %></td>
        <td><%= rm.max %></td>
        <td><%= link_to 'Show', rm %></td>
        <td><%= link_to 'Edit', edit_rm_path(rm) %></td>
        <td><%= link_to 'Destroy', rm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rm', new_rm_path %>

app/views/r_ms/new.html.erb
<h1>New Rm</h1>

<%= current_user.inspect if current_user %>

<div class="rm_form">
  <%= form_for(@rm) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.select :content, ['Back squat', 'Front squat', 'Deadlift',
                            'Sumo Deadlift', 'Sumo Deadlift High Pull',
                            'Power Snatch', 'Power Clean',
                            'Squat Clean', 'Muscle Snatch',
                            'Clean & Jerk', 'Thruster', 'Push Jerk',
                            'Split Jerk', 'Press',
                            'Push press', 'Cluster', 'Overhead Squat']%>

    <%= f.label :max, "Max reps" %>
    <%= f.text_field :max, class: 'form-control' %>

    <%= f.label :quantity, "Weight lifted" %>
    <%= f.text_field :quantity, class: 'form-control' %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

<%#= link_to 'Back', rms_path %>

app/views/r_ms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rm.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @rm.content %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @rm.quantity %>
</p>

<p>
  <strong>Max:</strong>
  <%= @rm.max %>
</p>

<%= link_to 'Edit', edit_rm_path(@rm) %> |
<%= link_to 'Back', rms_path %>